### PR TITLE
Refactor ItemList to ItemMap, fix minor help info typo

### LINKED ISSUE #77: Wrong output for "help delete"
Current: 
`help <index>`

Change to:
`help <name>`

### LINKED ISSUE #78: Refactor ItemList
Current issues include but are not limited to:
- If two instances of the same item with the same name are added, there is no way to access the second entry

### PR DESCRIPTION
**Pull request by yijiano**
Closes #77 
Closes #78

### CODE REVIEW

File: src/main/java/seedu/pill/util/ItemMap.java [hunk 1]
```diff
@@ -0,0 +1,180 @@
...
+
+    /**
+     * Adds a new item to the list.
+     *
+     * @param name     The name of the item.
+     * @param quantity The quantity of the item.
+     */
+    public void addItem(String name, int quantity) {
+        assert name != null && !name.trim().isEmpty() : "Item name cannot be null or empty";
+        assert quantity > 0 : "Quantity must be positive";
```
Comment (yakultbottle) [inline src/main/java/seedu/pill/util/ItemMap.java:39]: Good job using assertions and loggers in code

File: src/main/java/seedu/pill/util/ItemMap.java [hunk 2]
```diff
@@ -0,0 +1,180 @@
...
+        }
+        LOGGER.info("Searching for items containing: " + itemName);
+        for (Map.Entry<String, Item> entry : items.entrySet()) {
+            Item item = entry.getValue();
+            if (item.getName().toLowerCase().contains(itemName.toLowerCase())) {
+                foundItems.addItemSilent(item.getName(), item.getQuantity());
+            }
+        }
+        LOGGER.info("Found " + foundItems.items.size() + " items matching: " + itemName);
+        return foundItems;
```
Comment (yakultbottle) [inline src/main/java/seedu/pill/util/ItemMap.java:178]: Good job maintaining the usage of ItemList although the implementation was changed

**Review by yakultbottle — APPROVED** [review]
LGTM, nice refactor
