### PR TITLE
Bug Fixes for Help Command: Logging and Parser Corrections

### LINKED ISSUE #73: Logging Information Displayed in Console During Help Command Execution
Test that prompted this issue:
```
help
Oct 15, 2024 12:20:42 AM seedu.pill.command.HelpCommand <init>
INFO: Created HelpCommand with no specific command
Oct 15, 2024 12:20:42 AM seedu.pill.command.HelpCommand execute
INFO: Executing HelpCommand
Oct 15, 2024 12:20:42 AM seedu.pill.command.HelpCommand showGeneralHelp
INFO: Showing general help information
Available commands:
  help    - Shows this help message
  add     - Adds a new item to the list
  delete  - Deletes an item from the list
  edit    - Edits quantity of an existing item in the list
  list    - Lists all items
  quit    - Exits the program
Type 'help <command>' for more information on a specific command.
Add  '-v' after the command for verbose output with examples.
```

### LINKED ISSUE #74: Specific Help Command not working as intended
Test that triggered this issue:

```
help add
Oct 15, 2024 12:22:46 AM seedu.pill.command.HelpCommand <init>
INFO: Created HelpCommand with no specific command
Oct 15, 2024 12:22:46 AM seedu.pill.command.HelpCommand execute
INFO: Executing HelpCommand
Oct 15, 2024 12:22:46 AM seedu.pill.command.HelpCommand showGeneralHelp
INFO: Showing general help information
Available commands:
  help    - Shows this help message
  add     - Adds a new item to the list
  delete  - Deletes an item from the list
  edit    - Edits quantity of an existing item in the list
  list    - Lists all items
  quit    - Exits the program
Type 'help <command>' for more information on a specific command.
Add  '-v' after the command for verbose output with examples.
```

### PR DESCRIPTION
**Pull request by yakultbottle**
Closes #73, Closes #74

### CODE REVIEW

File: src/main/java/seedu/pill/util/Parser.java [hunk 1]
```diff
@@ -53,7 +53,8 @@ public void parseCommand(String input) throws PillException {
                 new FindCommand(argument).execute(this.items, this.storage);
                 break;
             case "help":
-                new HelpCommand().execute(this.items, this.storage);
+                boolean flag = quantityStr.equals("-v");
+                new HelpCommand(argument, flag).execute(this.items, this.storage);
```
Comment (yijiano) [inline src/main/java/seedu/pill/util/Parser.java:57]: Good job on making the verbose flag more clean

**Review by yijiano — APPROVED** [review]
LGTM
