### PR TITLE
Fix loadData exception handling, Parser exceptions, and help command …

### LINKED ISSUE #80: Exception Handling Bug
what happens right now is 
encounter corrupt line >> throw exception >> exception not handled by main >> program crashes

so even if i remove the line, although data loading works even with corrupt data, somewhere along the line if something just beneath the topmost methods throws an exception, the program will crash. This could also be a me issue for not having appropriate layers of abstraction.

### PR DESCRIPTION
**Pull request by yijiano**
Closes #80 

Added increased clarity for help and invalid command input.

Do note that I hard fixed the input to be 3 parameters (without spaces in between).

### CODE REVIEW

File: src/main/java/seedu/pill/command/HelpCommand.java [hunk 1]
```diff
@@ -55,7 +55,7 @@ private void showGeneralHelp() {
         System.out.println("  list    - Lists all items");
         System.out.println("  exit    - Exits the program");
         System.out.println("Type 'help <command>' for more information on a specific command.");
-        System.out.println("Add  '-v' after the command for verbose output with examples.");
+        System.out.println("Type 'help <command> -v' for verbose output with examples.");
```
Comment (yakultbottle) [inline src/main/java/seedu/pill/command/HelpCommand.java:58]: Nice refactor to make this message more coherent

File: src/main/java/seedu/pill/exceptions/ExceptionMessages.java [hunk 2]
```diff
@@ -1,12 +1,16 @@
...
 public enum ExceptionMessages {
-    INVALID_COMMAND         ("Invalid command, please try again."),
+    INVALID_COMMAND         ("Invalid command, please try again.\nType the 'help' command for a list of valid commands."),
     SAVE_ERROR              ("Error saving to file, please try again."),
     LOAD_ERROR              ("Error loading saved data"),
-    INVALID_LINE_FORMAT     ("Invalid line format, file corrupted"),
+    INVALID_LINE_FORMAT     ("File corrupted. Ignoring invalid line format..."),
     INVALID_QUANTITY        ("Quantity is invalid, please try again"),
-    INVALID_QUANTITY_FORMAT ("Quantity provided is not a number, please try again.");
+    INVALID_QUANTITY_FORMAT ("Quantity provided is not a number, please try again."),
```
Comment (yakultbottle) [inline src/main/java/seedu/pill/exceptions/ExceptionMessages.java:9]: Good job creating new Exceptions to handle errors

File: src/main/java/seedu/pill/util/Parser.java [hunk 3]
```diff
@@ -27,15 +27,18 @@ public Parser(ItemMap items, Storage storage) {
...
-        String argument = splitInput.length > 1 ? splitInput[1].toLowerCase() : null;
-        String quantityStr = splitInput.length > 2 ? splitInput[2] : "1"; // default quantity is 1
-
+    public void parseCommand(String input) {
         try {
+            String[] splitInput = input.split("\\s+");
+            if (splitInput.length > 3) {
+                throw new PillException(ExceptionMessages.TOO_MANY_ARGUMENTS);
+            }
+            assert(splitInput.length <= 3);
```
Comment (yakultbottle) [inline src/main/java/seedu/pill/util/Parser.java:37]: Good use of assert to guarantee the program functions as expected

**Review by yakultbottle — APPROVED** [review]
LGTM, nice fix

**Review by yakultbottle — APPROVED** [review]
